# Generated by Django 4.0.4 on 2022-05-29 00:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=20)),
                ('contrasena', models.CharField(max_length=20)),
                ('correo', models.CharField(max_length=30)),
            ],
        ),
    ]
